//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class acayear
    {
        public acayear()
        {
            this.curracayears = new HashSet<curracayear>();
            this.setfees = new HashSet<setfee>();
            this.payfees = new HashSet<payfee>();
            this.reimbursements = new HashSet<reimbursement>();
            this.concessions = new HashSet<concession>();
        }
    
        public int id { get; set; }
        public short year { get; set; }
    
        public virtual ICollection<curracayear> curracayears { get; set; }
        public virtual ICollection<setfee> setfees { get; set; }
        public virtual ICollection<payfee> payfees { get; set; }
        public virtual ICollection<reimbursement> reimbursements { get; set; }
        public virtual ICollection<concession> concessions { get; set; }
    }
}
