//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class cheque
    {
        public int id { get; set; }
        public int payFeeid { get; set; }
        public string bankName { get; set; }
        public string bankAddress { get; set; }
        public int chequenumber { get; set; }
        public System.DateTime dated { get; set; }
        public bool status { get; set; }
    
        public virtual payfee payfee { get; set; }
    }
}
