//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class college
    {
        public college()
        {
            this.depts = new HashSet<dept>();
        }
    
        public int collegeid { get; set; }
        public string collegeCode { get; set; }
        public string collegeName { get; set; }
    
        public virtual ICollection<dept> depts { get; set; }
    }
}
