//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class dept
    {
        public dept()
        {
            this.students = new HashSet<student>();
            this.sems = new HashSet<sem>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string desc { get; set; }
        public short duration { get; set; }
        public int collegeid { get; set; }
    
        public virtual college college { get; set; }
        public virtual ICollection<student> students { get; set; }
        public virtual ICollection<sem> sems { get; set; }
    }
}
