//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class feeEntities : DbContext
    {
        public feeEntities()
            : base("name=feeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<acayear> acayears { get; set; }
        public DbSet<batch> batches { get; set; }
        public DbSet<caste> castes { get; set; }
        public DbSet<cheque> cheques { get; set; }
        public DbSet<college> colleges { get; set; }
        public DbSet<concession> concessions { get; set; }
        public DbSet<curracayear> curracayears { get; set; }
        public DbSet<dept> depts { get; set; }
        public DbSet<feetype> feetypes { get; set; }
        public DbSet<payfee> payfees { get; set; }
        public DbSet<paymenttype> paymenttypes { get; set; }
        public DbSet<quota> quotas { get; set; }
        public DbSet<reimbursement> reimbursements { get; set; }
        public DbSet<rolemoduleactionpermission> rolemoduleactionpermissions { get; set; }
        public DbSet<rolemoduleaction> rolemoduleactions { get; set; }
        public DbSet<rolemodulepermission> rolemodulepermissions { get; set; }
        public DbSet<rolemodule> rolemodules { get; set; }
        public DbSet<role> roles { get; set; }
        public DbSet<sem> sems { get; set; }
        public DbSet<setfee> setfees { get; set; }
        public DbSet<student> students { get; set; }
        public DbSet<user> users { get; set; }
    }
}
