//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class feetype
    {
        public feetype()
        {
            this.concessions = new HashSet<concession>();
            this.payfees = new HashSet<payfee>();
            this.setfees = new HashSet<setfee>();
        }
    
        public int id { get; set; }
        public string type { get; set; }
        public short allowedInstallments { get; set; }
    
        public virtual ICollection<concession> concessions { get; set; }
        public virtual ICollection<payfee> payfees { get; set; }
        public virtual ICollection<setfee> setfees { get; set; }
    }
}
