//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class role
    {
        public role()
        {
            this.rolemoduleactionpermissions = new HashSet<rolemoduleactionpermission>();
            this.rolemodulepermissions = new HashSet<rolemodulepermission>();
            this.users = new HashSet<user>();
        }
    
        public int id { get; set; }
        public string roleName { get; set; }
    
        public virtual ICollection<rolemoduleactionpermission> rolemoduleactionpermissions { get; set; }
        public virtual ICollection<rolemodulepermission> rolemodulepermissions { get; set; }
        public virtual ICollection<user> users { get; set; }
    }
}
