//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class rolemoduleactionpermission
    {
        public int id { get; set; }
        public int roleid { get; set; }
        public int rolemoduleactionid { get; set; }
        public bool permission { get; set; }
    
        public virtual role role { get; set; }
        public virtual rolemoduleaction rolemoduleaction { get; set; }
    }
}
