//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class rolemoduleaction
    {
        public rolemoduleaction()
        {
            this.rolemoduleactionpermissions = new HashSet<rolemoduleactionpermission>();
        }
    
        public int id { get; set; }
        public int rolemoduleid { get; set; }
        public string name { get; set; }
        public string displayname { get; set; }
    
        public virtual ICollection<rolemoduleactionpermission> rolemoduleactionpermissions { get; set; }
        public virtual rolemodule rolemodule { get; set; }
    }
}
