//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public student()
        {
            this.concessions = new HashSet<concession>();
            this.payfees = new HashSet<payfee>();
            this.reimbursements = new HashSet<reimbursement>();
            this.setfees = new HashSet<setfee>();
        }
    
        public int id { get; set; }
        public string htno { get; set; }
        public string name { get; set; }
        public string fname { get; set; }
        public int casteid { get; set; }
        public int quotaid { get; set; }
        public int batchid { get; set; }
        public int deptid { get; set; }
        public int semid { get; set; }
        public bool feeExemption { get; set; }
    
        public virtual batch batch { get; set; }
        public virtual caste caste { get; set; }
        public virtual ICollection<concession> concessions { get; set; }
        public virtual dept dept { get; set; }
        public virtual ICollection<payfee> payfees { get; set; }
        public virtual quota quota { get; set; }
        public virtual ICollection<reimbursement> reimbursements { get; set; }
        public virtual sem sem { get; set; }
        public virtual ICollection<setfee> setfees { get; set; }
    }
}
